name: Deployment App
on:
  push:
    branches:
      - main

jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - name: Print
        run: echo Initializing Deployment Process
  build:
    runs-on: ubuntu-latest
    needs: init
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Use nodejs
        uses: actions/setup-node@v4
        with:
          node-version: "19"
      - name: Install dependencies
        run: npm install
      - name: Build app
        run: npm run build
